# Generated by Django 5.2.8 on 2025-11-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('Reference_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=100)),
                ('Date_Of_Manufacture', models.DateField()),
                ('Colour', models.CharField(max_length=50)),
                ('Max_Retail_Price', models.FloatField()),
                ('Feedback', models.TextField()),
            ],
        ),
    ]
